user:
  default:
    # 用户名的默认前缀
    username: user
    # 用户的默认头像
    avatar: http://d.lanrentuku.com/down/png/1904/business_avatar/8_avatar_2754583.png

server:
  port: 9527 # 这个端口要和vue项目里vue.config.js里的devServer里面配置的相同
  servlet:
    context-path: /api
spring:
  application:
    name: service-exam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # 调试的时候用，用于打印完成SQL语句(但是不打印参数),联合下面的logging.level一同打印最完整的SQL信息(语句+参数)
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小
  profiles:
    active: dev # 开发时配dev, 生产环境配prod，如果容器化直接运行make_docker.sh即可这里配啥无所谓

# 拦截器相关的配置
interceptors:
  # 不需要进行鉴权的接口地址，用逗号隔开
  auth-ignore-uris: ${server.servlet.context-path}/user/register,${server.servlet.context-path}/user/login

# SQL语句打印(能打印参数，设置为trace是打印完整语句，默认我们就关掉吧)
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: off
