ip:
  base: 127.0.0.1

user:
  default:
    # 用户名的默认前缀
    username: user
    # 用户的默认头像
    avatar: http://d.lanrentuku.com/down/png/1904/business_avatar/8_avatar_2754583.png

server:
  port: 9527

spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxxxxx
    url: jdbc:mysql://${ip.base}:3306/exam?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    # 调试的时候用，用于打印完成SQL语句(但是不打印参数),联合下面的logging.level一同打印最完整的SQL信息(语句+参数)
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小

# 拦截器相关的配置
interceptors:
  # 不需要进行鉴权的接口地址，用逗号隔开
  auth-ignore-uris: /user/register,/user/login

# SQL语句打印(能打印参数，设置为trace是打印完整语句，默认我们就关掉吧)
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: off